### PR TITLE
34 header html css

### PR DESCRIPTION
**Pull request by elios11**
localhost_5173_(BEFEDA Project Mobile size)

### CODE REVIEW

**Review by fgomensoro — APPROVED** [review]

**Review by fgomensoro — CHANGES_REQUESTED** [review]
Here are same changes as PR 70. This PR should be dismissed

**Comment by elios11** [comment]
> Here are same changes as PR 70. This PR should be dismissed
They are dependant branches, the tablet one is based on this one, and the desktop one is based on the tablet one. Each one adds the new changes for each view

**Review by fgomensoro — APPROVED** [review]

**Comment by fgomensoro** [comment]
> > Here are same changes as PR 70. This PR should be dismissed
> > They are dependant branches, the tablet one is based on this one, and the desktop one is based on the tablet one. Each one adds the new changes for each view

I approved it. But its the same code. 
If you make a new branch form another branch that it was not merged to main then it takes all the commits from both branches in the PR. Because all are differences that it has from main.

**Comment by elios11** [comment]
> > > Here are same changes as PR 70. This PR should be dismissed
> > > They are dependant branches, the tablet one is based on this one, and the desktop one is based on the tablet one. Each one adds the new changes for each view
> 
> I approved it. But its the same code. If you make a new branch form another branch that it was not merged to main then it takes all the commits from both branches in the PR. Because all are differences that it has from main.

Yeah but I mean, the idea is to merge this branch first, then those commits will already be in main, then merge the tablet one, and then the desktop one. This will only keep the new commits for each branch as expected, or am I wrong? o.O

I don't think there's something wrong with working with branches made from other branches, git is smart enough to know when to add a commit or not, and this allows me to make new changes in a new branch while having the previous ones available for visualization.

**Review by valselviz — APPROVED** [review]

**Pull request merged**
